
version: 2.1

executors:
  normal_container:
    docker:
      - image: cimg/node:lts

jobs:
  unit-test:
    executor: normal_container
    steps:
      - checkout
      - run:
          name: unit-test
          command: |
            echo "run unit-test"

            circleci-agent step halt

            echo "running??"

            sleep 10

            echo "running????"
      - run:
          name: unit-test-2
          command: |
            echo "run unit-test-2"

            sleep 5

            echo "running unit-test-2"
      - checkout
      - checkout
      - restore_cache:
          key: v1-myapp-cache
      - save_cache:
          key: v1-myapp-cache-new
          paths:
            - ~/d2

  deploy:
    executor: normal_container
    steps:
      - run:
          name: deploy
          command: |
            echo "run deploy"

            circleci-agent step halt

            echo "running??"

            sleep 10

            echo "running????"
      - run:
          name: deploy-2
          command: |
            echo "run deploy-2"

            sleep 5

            echo "running deploy-2"
      - checkout
      - checkout
      - restore_cache:
          key: v1-myapp-cache
      - save_cache:
          key: v1-myapp-cache-new
          paths:
            - ~/d2

workflows:
  release:
    jobs:
      - unit-test
      - deploy:
          requires:
            - unit-test
